# Generated by Django 4.2.4 on 2023-09-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('plataforma', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desenvolvedor')),
            ],
        ),
    ]
